### ISSUE TITLE
nvm file

### ISSUE THREAD

**Issue by jaswant7** [SBCV/Blender-Addon-Photogrammetry-Importer#10]
When nvm is imported in blender, the rendered image using camera position and orientation does not generate same image as corresponding to given RGB image.

I think origin changes when nvm is imported in Blender.

And can you please help to load RGB values corresponding to point cloud ?

Thanks

**Comment by SBCV** [comment]
Can you share a corresponding example? That would simplify the debugging process.

**Comment by jaswant7** [comment]
Thanks for your reply.

Yes. I used the famous Cambridge Landmark dataset, I used the reconstructed.nvm file and imported in blender. Then I tried to render image using  camera pose, But it was not correct.

**Comment by SBCV** [comment]
It would be very helpful if you could share / upload the file, since the content of the nvm file depends on the used software and the reconstruction options.

**Comment by SBCV** [comment]
Furthermore, which scene have you used? King's College, Street, Old Hospital, Shop Facade, St Mary's Church or Trinity Great Court?

**Comment by jaswant7** [comment]
I tried to upload the file, but couldn't because of size. I'm sharing the link.

http://mi.eng.cam.ac.uk/projects/relocalisation/

I tried with king's college and St Mary's Church. These files are reconstructed using vsfm. The dataset also contains camera poses and corresponding RGB images.

Thanks

**Comment by SBCV** [comment]
I checked the nvm file provided in the dataset. It contains relative paths of images in different subfolders with duplicate names - this is currently not supported. I'll fix this in the next few days.

Considering the the alignment of images: Have you read the following part of the documentation? 

See the images in [alignment](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/master/doc/markdown/alignment.md)

Furthermore, [usage](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/master/doc/markdown/usage.md#nvm) states that: "The addon automatically looks for the fixed calibration line in the NVM file (i.e. "NVM_V3 FixedK fx cx fy cy r" (first line)). Without the fixed calibration line the addon assumes that the principal point is at the image center. NVM files contain no information about the size of the images. Use the import dialog to adjust the "image path" to automatically read the image size from disc or set the default "width" and "height" values."

Bests

**Comment by jaswant7** [comment]
Thanks for your reply.

I have added fixed calibration line in nvm file and i have seen Alignment part. But my main consideration was, for example if i add camera in blender after loading nvm file and use camera pose given in data train file "seq8/frame00064.png -9.123465 -13.208417 1.722406 0.683091 0.543983 -0.314596 0.372154" i.e, xyzwpqr and see view from camera, it should give view corresponding to image given in "seq8/frame00064.png". It should be same. But in my case it is not same.

Sorry if i'm wrong some where. Hope I was able to explain.

Thanks again

**Comment by SBCV** [comment]
Sorry for the late reply. 
Many changes have been required to support relative paths. With the latest commit you should be able to import the results of the Cambridge Landmark dataset. 
(You need to replace "jpg" in the provided "KingsCollege\reconstruction.nvm" file with "png", since the image data consists actually of png images.)
In order to use relative paths contained in the nvm file, select the corresponding option in the addon (in the latest version!)
![Anmerkung 2020-03-07 150419](https://user-images.githubusercontent.com/19491335/76144902-f32d4000-6084-11ea-9cfc-6bd3f8b78d52.jpg)


As you can see in the following screen shots, the cameras align correctly with the image data.

Background image of some camera:
![Anmerkung 2020-03-07 130123](https://user-images.githubusercontent.com/19491335/76144822-4652c300-6084-11ea-999a-fb6e98c0484a.jpg)

Background image of some camera with imported point cloud:
![Anmerkung 2020-03-07 130050](https://user-images.githubusercontent.com/19491335/76144834-55397580-6084-11ea-8f36-80695e32ec7e.jpg)

Therefore , I'm afraid I do not understand your question.

**Comment by jaswant7** [comment]
Thanks for your reply.
Sorry for late replying.

Your last reply solved my problem.

**Comment by SBCV** [comment]
Nice :)

**Comment by SBCV** [comment]
Btw the addon supports now an option, which allows you to draw the points with opengl 
![import_result_opengl](https://user-images.githubusercontent.com/19491335/76468873-4daffe80-63ed-11ea-9108-90dfc4359147.jpg)

**Comment by jaswant7** [comment]
Thanks for your help.
And how can we see colored point cloud while loading nvm file.
I also tried by creating a ply file from nvm file and loading in blender.

Thanks again

**Comment by SBCV** [comment]
You need to set the viewport shading to rendered (using cycles) - see red rectangle below.
![Viewport_shading](https://user-images.githubusercontent.com/19491335/76708530-cd90de00-66f7-11ea-9fcb-8bd49a4100ab.jpg)

If that does not work, please test with the examples provided in this repository.

**Comment by jaswant7** [comment]
Thanks for your reply

Sorry. But I think it does not load RGB values from nvm file.

**Comment by SBCV** [comment]
You need to provide some more information - so I can help you.
Please describe precisely what you have done so far, i.e. 
Step 1
Step 2
...

**Comment by jaswant7** [comment]
one way: I tried loading nvm file  directly from your addon.
another way : I converted nvm file to ply file and tried loading with your addon.

Both these didn't work.

**Comment by jaswant7** [comment]
And I usually run blender from command line. And can i write python script to use your addons ?

Thanks

**Comment by SBCV** [comment]
Did you test with the example nvm/ply file in the repository?

The source code is published under the [MIT license](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/master/LICENSE) - therefore, yes, you can.

**Comment by jaswant7** [comment]
Earlier I was using these commands for file import(in python script) and rendering images:

ob = bpy.ops.import_mesh.ply(filepath="path_to_file")
lamp_data = bpy.data.lamps.new(name='lamp', type='POINT')
lamp = bpy.data.objects.new(name='lamp', object_data=lamp_data)
lamp.location = (c_loc[0],c_loc[1],c_loc[2])
scene = bpy.context.scene

bpy.ops.object.camera_add(view_align=False,
                          location=[c_loc[0],c_loc[1],c_loc[2]],
                          rotation=[c_r[0],c_r[1],c_r[2]])
scene.camera = bpy.context.object
But now to import point_cloud ply import with "Draw point....wit OpenGL" what should I use ?

Sorry If I am asking very basic questions.

Thanks

**Comment by jaswant7** [comment]
Yes I have tested with example. But it was also not showing coloured point cloud.

**Comment by SBCV** [comment]
Ah, I see, you are trying to render the point cloud with opengl. 
Also for me, rendering the point cloud with with opengl does not produce any colors - this looks like a Blender bug. I'm afraid, I can not help you here. But we could create a Blender bug report.

But you can render the point cloud with cycles. (In this case you can not use lamps to create scene illuminations, but for example environment maps).

**Comment by SBCV** [comment]
And by the way: `bpy.ops.import_mesh.ply(filepath="path_to_file")` is not part of this addon, this is Blender's built-in ply loading function

**Comment by SBCV** [comment]
I just realized that the render functionality of blender does not render the opengl points at all - the black points are the vertices of the Blender object, which represents the point cloud. Currently, the opengl points "occlude" these object vertices. You can see this by moving either the "Point Cloud" or the "point_cloud_drawing_handle" (see below)
![point_cloud_visualization](https://user-images.githubusercontent.com/19491335/77260614-76f04a80-6c89-11ea-99aa-decdd6b5a81f.jpg)

**Comment by jaswant7** [comment]
Thanks for your explaination. It was good.

So what should be my approach to take images from point cloud(nvm) using camera poses. ?

**Comment by SBCV** [comment]
Represent the point cloud with a particle system and render it with cycles (there is a corresponding import option for ply, nvm, ...)

**Comment by jaswant7** [comment]
I tried but could not take images with diff camera poses.(maybe i'm wrong somewhere)

Thanks for patience

**Comment by SBCV** [comment]
Please follow these steps.
1.) Install the latest version of this addon in Blender
2.) Open the the example ply file (Blender-Addon-Photogrammetry-Importer/examples/example.ply) using the ply importer of the addon
![Anmerkung 2020-03-25 010819](https://user-images.githubusercontent.com/19491335/77488332-27e71880-6e35-11ea-981b-f235d1785010.jpg)

3.) The corresponding import options SHOULD look as follows (i.e. add points as particle system):
![Anmerkung 2020-03-25 010051](https://user-images.githubusercontent.com/19491335/77488187-c9219f00-6e34-11ea-8c98-5cef93c9a382.jpg)

4.) Add a camera that points on the point cloud. 
5.) Set the viewport shading to rendered (using cycles) - see red rectangle below.
![76708530-cd90de00-66f7-11ea-9fcb-8bd49a4100ab](https://user-images.githubusercontent.com/19491335/77488486-a5ab2400-6e35-11ea-9c12-b8808990eb2b.jpg)
6.) Render the scene

Does that work for you? Do you see the point cloud with colors?
