### ISSUE TITLE
Accessing this addon from Python script for batch processing

### ISSUE THREAD

**Issue by georgie-png** [SBCV/Blender-Addon-Photogrammetry-Importer#13]
Hey, 

Really helpful addon, thanks!

I am just trying to use it as part of a batch processing pipeline that takes in videos in to colmap, produce 3d point clouds and render them out from the camera angles, so this is really helpful. There are roughly 50 different vids/objs so it would be great to be able to write a script to run through them all and import each one at a time with this addon. 

I had a look at your code a bit and a bit elsewhere, could it be accessed through bpy.import? or would you recommend i try to access the classes directly from your scripts?

Thanks a lot and great work,
George

**Comment by georgie-png** [comment]
worked it out,

load colmap:
bpy.ops.import_scene.colmap_model(directory="path/to/directory/")

with all args : 
bpy.ops.import_scene.colmap_model(import_cameras=True, default_width=-1, default_height=-1, default_focal_length=nan, default_pp_x=nan, default_pp_y=nan, add_background_images=False, add_image_planes=True, image_fp_type='NAME', image_dp="", add_image_plane_emission=True, image_plane_transparency=0.5, add_camera_motion_as_animation=True, number_interpolation_frames=0, interpolation_type='LINEAR', consider_missing_cameras_during_animation=True, remove_rotation_discontinuities=True, adjust_render_settings=True, camera_extent=1, import_points=True, draw_points_with_gpu=False, add_points_as_particle_system=True, mesh_type='CUBE', point_extent=0.01, add_particle_color_emission=True, set_particle_color_flag=False, particle_overwrite_color=(0, 1, 0), directory="")

**Comment by SBCV** [comment]
Hey, I'm glad you figured it out. 
For executing python scripts with Blender I highly recommend [VS Code](https://code.visualstudio.com) with this [extension](https://marketplace.visualstudio.com/items?itemName=JacquesLucke.blender-development). 
This allows to perform fast development and validation cycles with Blender scripts and Addons. 
[Here](https://www.youtube.com/watch?v=q06-hER7Y1Q) is an introduction / tutorial video.

**Comment by SBCV** [comment]
FYI
https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/master/doc/markdown/python.md
