### ISSUE TITLE
Cannot import openmvg json camera

### ISSUE THREAD

**Issue by SteampunkIslande** [SBCV/Blender-Addon-Photogrammetry-Importer#16]
Hi ! First of all, thank you so much for this addon, it could help me a lot for with I'm trying to do !

So here's the problem: I used Regard3D (http://www.regard3d.org/) which is an awesome tool for photogrammetry. I found that it creates a sfm scene (sfm_data.bin)

I successfully converted this bin file into json thanks to openMVG usign these options (-V -I -E). So I get a json file with view ids, intrinsics and extrinsics. These should be enough for json import, though I ran into this weird error:

Traceback (most recent call last):
  File "C:\Users\Charles\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\photogrammetry_importer\photogrammetry_import_op.py", line 180, in execute
    path, self.image_dp, self.image_fp_type, self)
  File "C:\Users\Charles\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\photogrammetry_importer\file_handler\openmvg_json_file_handler.py", line 169, in parse_openmvg_file
    cams = OpenMVGJSONFileHandler.parse_cameras(json_data, image_dp, image_fp_type, op)
  File "C:\Users\Charles\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\photogrammetry_importer\file_handler\openmvg_json_file_handler.py", line 50, in parse_cameras
    polymorphic_name = intrinsics[int(id_intrinsic)]['value']['polymorphic_name']
KeyError: 'polymorphic_name'

Here is how the intrinsics look like after conversion:

"intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "pinhole_radial_k3",
                "ptr_wrapper": {
                    "id": 2147483745,
                    "data": {
                        "width": 4000,
                        "height": 6000,
                        "focal_length": 15193.06853136843,
                        "principal_point": [
                            2010.6631635894829,
                            3013.5288307892844
                        ],
                        "disto_k3": [
                            0.23547542621624013,
                            1.0377324669468973,
                            25.664009974069687
                        ]
                    }
                }
            }
        },
        {
            "key": 1,
            "value": {
                "polymorphic_id": 1,
                "ptr_wrapper": {
                    "id": 2147483746,
                    "data": {
                        "width": 6000,
                        "height": 4000,
                        "focal_length": 26837.64213005792,
                        "principal_point": [
                            3024.948789263701,
                            2005.5551594699007
                        ],
                        "disto_k3": [
                            1.308115485771672,
                            23.88648384690404,
                            -560.0914521542329
                        ]
                    }
                }
            }
        },
        {
            "key": 2,
            "value": {
                "polymorphic_id": 1,
                "ptr_wrapper": {
                    "id": 2147483747,
                    "data": {
                        "width": 6000,
                        "height": 4000,
                        "focal_length": 25512.9448045926,
                        "principal_point": [
                            3061.900325109015,
                            1997.2968905128087
                        ],
                        "disto_k3": [
                            1.5001251036783452,
                            -26.644358754059213,
                            1921.1474880697998
                        ]
                    }
                }
            }
        },
        {
            "key": 3,
            "value": {
                "polymorphic_id": 1,
                "ptr_wrapper": {
                    "id": 2147483748,
                    "data": {
                        "width": 4000,
                        "height": 6000,
                        "focal_length": 14108.98059220295,
                        "principal_point": [
                            2004.5743060023872,
                            3021.6981645876114
                        ],
                        "disto_k3": [
                            0.136069949695253,
                            0.7672774745376262,
                            16.480312185674408
                        ]
                    }
                }
            }
        },
        {
            "key": 4,
            "value": {
                "polymorphic_id": 1,
                "ptr_wrapper": {
                    "id": 2147483749,
                    "data": {
                        "width": 6000,
                        "height": 4000,
                        "focal_length": 14123.264459113307,
                        "principal_point": [
                            3046.6720924000785,
                            2035.155786688224
                        ],
                        "disto_k3": [
                            0.03136966972788541,
                            7.1919426547408709,
                            -114.82146264426034
                        ]
                    }
                }
            }
        },
        {
            "key": 5,
            "value": {
                "polymorphic_id": 1,
                "ptr_wrapper": {
                    "id": 2147483750,
                    "data": {
                        "width": 6000,
                        "height": 4000,
                        "focal_length": 17775.452419755573,
                        "principal_point": [
                            3034.855326792158,
                            2035.176286944217
                        ],
                        "disto_k3": [
                            0.42808247529376267,
                            6.4239000531778649,
                            -58.24064251915535
                        ]
                    }
                }
            }
        }
    ]

Does anyone have an idea why the poylmorphic_name is not consistent throughout the intrinsics ?
This is untouched, from openMVG, and using only one dataset.

Thanks in advance :)

**Comment by SBCV** [comment]
Could you share somehow the json file with me? This would simplify the debugging process. If you need a small scene I would recommend the the sceaux dataset (https://github.com/openMVG/ImageDataset_SceauxCastle).
Btw, I think it would make sense to extend this addon to support Regard3d as well. However, need to check how difficult it is to parse these .bin files

**Comment by SBCV** [comment]
But from the json file you have posted one can see that 
`"polymorphic_name": "pinhole_radial_k3" `
is only present for 
`"key": 0`
 which is a bit weird. 
So I guess a workaround would be to add these values for the other keys as well. Of course this is not a reasonable long term solution, and we should fix the source code instead.

**Comment by SteampunkIslande** [comment]
> 
> 
> But from the json file you have posted one can see that
> `"polymorphic_name": "pinhole_radial_k3" `
> is only present for
> `"key": 0`
> which is a bit weird.
> So I guess a workaround would be to add these values for the other keys as well. Of course this is not a reasonable long term solution, and we should fix the source code instead.

I already found this and tried the trick you suggest, but it creates other errors I didn't understand...
I'm trying with Sceaux Castle dataset to test Regard3d with the workflow described above, I'll tell you.

Also thanks for this quick answer !

**Comment by SBCV** [comment]
If you share the file with me, I'll have a look.
If the file contains correct / consistent information, parsing with the addon should be "relatively" easy, since the conversion / transformation functions are already there. 
One thing that could currently cause problems is the fact, that these cameras have 3 radial distortion parameters. I think the addon assumes, that these should be 0, since a reasonable visualization with Blender is with 3 distortion parameters not possible (and in the case of the sceaux castle, there is no radial distortion anyways). Does regard3d allow to set the radial distortion to 0 during triangulation?

**Comment by SteampunkIslande** [comment]
OK, then to save you some time this is what the intrinsics look like in the file generated from the Regard3D->openMVG workflow described previously

"intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "pinhole_radial_k3",
                "ptr_wrapper": {
                    "id": 2147483660,
                    "data": {
                        "width": 2832,
                        "height": 2128,
                        "focal_length": 2987.0843387468355,
                        "principal_point": [
                            1484.5691275563345,
                            1116.9255806571615
                        ],
                        "disto_k3": [
                            -0.2439353999782101,
                            0.2579182467439407,
                            0.1528921100785811
                        ]
                    }
                }
            }
        }
    ],

As you can see, there is this 'disto_k3' field, and as you state radial k3 is not supported.
(The same assertion failure line 67 I got when copy pasting polymorphic_name attribute as you suggested earlier).


[cameras.txt](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/files/4663914/cameras.txt)

Above I attach the full json file, but I'm pretty sure the rest of it is already OK for the openMVG parser.

**Comment by SteampunkIslande** [comment]
All right, figured out a solution ! As you said, radial k3 is not supported. So if anyone is wondering, the trick is to chose Pinhole in the camera model drop down menu when computing matches in Regard3D.
So the complete workflow is as follow (assuming you're familiar with Regard3D and Blender):

- First compute matches using pinhole camera model (not pinhole radial 3 !)
- Next compute triangulation (any parameter should work)
- Then find the directory where the triangulation was done, it should be like
Path/to/your/project/pictureset_0/matching_0/triangulation_0
You will find a file named sfm_data.bin

Download openMVG (if on windows you can find the binaries here https://github.com/openMVG/openMVG/releases/). Unfortunately for mac and linux you will have to compile yourself)

In the openMVG directory, run the following command:
openMVG_main_ConvertSfM_DataFormat.exe -i "Path/to/sfm_data.bin"  -o "Path/to/cameras.json" -V -I -E

Make sure to use the three options, and not the -S and -C options (they are for exporting the whole structure which is too big for json format, blender might explode)

- Last, all you have to do is open up blender, chose import from openMVG (.json) and select the last file you created (cameras.json)

And that's it !

**Comment by SBCV** [comment]
I changed the default handling of radial distortion parameters. Now you can directly import reconstructions computed with the `radial k3` camera model (Corresponding warnings are thrown). And for the best alignment of cameras and points, I highly recommend to disable radial distortion if possible (i.e. in cases where the true camera lens has no or only a marginal distortion).

If I have more time, I'll check if it is possible to import the bin files directly. 

Considering 
> Make sure to use the three options, and not the -S and -C options (they are for exporting the whole structure which is too big for json format, blender might explode)

I don't know how big your point cloud is, but maybe this depends on your settings. You can draw the points with OpenGL (setting provided by the addon). This will decrease the computational requirements. 
In fact I've just changed the default import settings of the addon. The latest version will add the points with OpenGL by default (which is way cheaper than the particle system)

Make also sure you install pillow for blender (see installation instructions [here](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/master/doc/markdown/installation.md#optional-dependency-for-visualsfm-and-openmvgregard3d-files)), so you can see the color information of openmvg/regard3d point clouds.
