### ISSUE TITLE
Typo: sceene.frame_end -> scene.frame_end

### ISSUE THREAD

**Issue by JasonLiJT** [SBCV/Blender-Addon-Photogrammetry-Importer#19]
Thx for this great addon!

I spotted a typo here: https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/e60a6803fe7284be7bb932f598e81b4ebd9035d0/photogrammetry_importer/panel/opengl_panel.py#L242

This triggered an error when I used the OpenGL Panel -> uncheck "Use Camera Keyframes" -> Export as Animation.

**Comment by SBCV** [comment]
Thank you for reporting this - fixed in the latest version.
