### ISSUE TITLE
Not installing in Blender 2.83.5, does not show up in list for Activation

### ISSUE THREAD

**Issue by brianlrichards** [SBCV/Blender-Addon-Photogrammetry-Importer#23]
Not installing in Blender 2.83.5, does not show up in list for Activation

**Comment by SBCV** [comment]
Thx for reporting this, I'll have a look and come back to you.

**Comment by SBCV** [comment]
Unfortunately, I could not reproduce your issue. Both, the latest version as well as the release (https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/files/4810367/photogrammetry_importer.zip) worked without any problems. 
Can you provide some more information?

**Comment by SBCV** [comment]
Ah, one reason could be that "Community" is not selected. See the image below:

![Selection_020](https://user-images.githubusercontent.com/19491335/91158246-a555d400-e6c6-11ea-9f20-32c8983581b4.png)

**Comment by SBCV** [comment]
Also, a wrong entry in the search box ("pho" in the image above) could hide the photogrammetry addon entry.

**Comment by SBCV** [comment]
Have you been able to fix the problem?

**Comment by SBCV** [comment]
Feel free to reopen
