### ISSUE TITLE
Not an issue - but a request!

### ISSUE THREAD

**Issue by solosails** [SBCV/Blender-Addon-Photogrammetry-Importer#30]
Hi, 

Thank you for this amazing set of tools - really really handy!

I use Meshroom, which is all working brilliantly for me, and I particularly love the way the cameras import allows interpolation and animation of the actual camera points - 

I also use Metashape from agisoft (will output from this be possible to import in the future?) , but for now, I can import the cameras and model using Alembic ex/import, but it does not create the keyframe animation - are you able to explain the process of animating between the fixed positions? - Thanks!

**Comment by SBCV** [comment]
I've not worked with metashape myself, but adding support for it is something we can look into. 
What file formats does it support? If you could share an example reconstruction of the [sceaux castle](https://github.com/openMVG/ImageDataset_SceauxCastle) (like in [Blender-Addon-Photogrammetry-Importer/examples](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/tree/master/examples)) this would simplify the process a lot.

To see what the animation does, have a look at:
`add_camera_animation()` in [photogrammetry_importer/utility/blender_camera_utility.py](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/a38031c4815aabf6d049faf26be1c92ba3c6212e/photogrammetry_importer/utility/blender_camera_utility.py#L212) 
and
`add_transformation_animation()` in [photogrammetry_importer/utility/blender_animation_utility.py](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/master/photogrammetry_importer/utility/blender_animation_utility.py)

In `add_transformation_animation()` you can see that the addon uses simply Blender's `fcurve` interpolation functionality to define the interpolation. In addition, the addon ensures that the quaternions (representing the camera motion) show the same sign. This is important to avoid strange results.

Does that help?

**Comment by solosails** [comment]
Hi Sebastian,

Thank you very much for taking the time to point me in the right direction - really helpful.

RE metashape - I have attached a low res working file from the Sceaux castle set for you to take a look at.

RE export types, it can manage quite a few depending on whether you are exporting the mesh, the pointcloud, the camera, the depth maps etc - but the image is of the export options when exporting the textured model ...
![Metashape_File_Types](https://user-images.githubusercontent.com/7858421/99946134-c2557e00-2d6d-11eb-9ce7-93a47f960fd2.jpg)

[Sceaux_Castle_Metashape.zip](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/files/5581981/Sceaux_Castle_Metashape.zip)

You can download and use Metashape for free for the first 30 days I believe - 

Thanks for your help!

**Comment by SBCV** [comment]
Since you are primarily interested in importing the camera motion, could you also share a screen shot of the formats that allow to export camera information?

Btw: The Sceaux_Castle_Metashape.zip file you've uploaded does not contain any reconstruction data.

**Comment by SBCV** [comment]
I found this [library for collada](https://github.com/pycollada/pycollada), which could be an option to import metashape reconstructions, since it can be installed with `pip install pycollada`. Can you export your reconstruction as `.dae` file and post here too?

**Comment by solosails** [comment]
> Since you are primarily interested in importing the camera motion, could you also share a screen shot of the formats that allow to export camera information?
> 
> Btw: The Sceaux_Castle_Metashape.zip file you've uploaded does not contain any reconstruction data.

Hi Sebastian, 

Sorry about the attached file, I assumed you wanted Metashape's native save file which is what I attached. 

RE collada, yes, it can export .dae, I have attached the Sceaux example (again, very quick and low res build)
[Sceaux_Castle.zip](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/files/5595484/Sceaux_Castle.zip)

RE camera imports from 
![cameras](https://user-images.githubusercontent.com/7858421/100205159-a7654400-2efc-11eb-9a46-cf2e9fe1e7ec.jpg)

There is a plugin by Uhlik for importing to Blender Metashape's native camera file (XML) https://github.com/uhlik/bpy#import-agisoft-photoscan-cameras - however, this doesn't really do any more than simply using blender's native Alembic format, but might be worth looking at - I think I noticed he had helped you with the pointcloud part of your addon? 

So, I must say a big thank you for taking the time to look at all this for me, and I also must apologize that I am not a coder, so cannot be of much assistance other than sending file formats if required - thank you!

**Comment by SBCV** [comment]
> Sorry about the attached file, I assumed you wanted Metashape's native save file which is what I attached.

The file `Sceaux_Castle_Metashape.zip` contains currently only the following two lines
```
<?xml version="1.0" encoding="UTF-8"?>
<document version="1.2.0" path="{projectname}.files/project.zip"/>
```

> RE camera imports from
![100205159-a7654400-2efc-11eb-9a46-cf2e9fe1e7ec](https://user-images.githubusercontent.com/19491335/100211318-46456c80-2f0c-11eb-922d-c5192e73f026.jpg)

Are these the **import** or the **export** options? (Because you've wrote `RE camera imports from`)
If these are the **import** options, please post the **export** options.
If these are the **export** options, you can export it to the (*.nvm) format, which is already supported by this addon. 

Thank you for pointing out the script by Uhlik. According to the description (`Import cameras from Agisoft PhotoScan xml.`) this imports an `xml` file. This is another option, which should be easy to implement. In this case please post the xml file exported from your sceaux castle reconstruction.

**Comment by solosails** [comment]
Hi, The link on my last post has the caollada file in it. (or at least that's what is in it when I download the file)

Sorry for confusion - these are the list of camera export file options.

I have attached the .nvm format for you.
[sceaux_cams.zip](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/files/5596066/sceaux_cams.zip)

[Sceaux_cams_xml.zip](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/files/5596087/Sceaux_cams_xml.zip)

Hope these work.

**Comment by solosails** [comment]
I can confirm I am able to import the Metashape .nvm file into blender using your addon, which surprisingly imports the pointcloud (even though I just exported the cameras) but it doesn't appear to import the cameras

**Comment by SBCV** [comment]
I can import your nvm file without problems. Just use the nvm-importer of this addon.
That means: in Blender select `File/import/VisualSfM (.nvm)`, then set the path to `sceaux_cams.nvm` and in the corresponding import options set `Image Directory` to the directory of your input images. I've read that you can also export the undistorted images with metashape. This will remove radial distortions effects - read more about this [here](https://blender-addon-photogrammetry-importer.readthedocs.io/en/latest/alignment.html).

**Comment by SBCV** [comment]
> I can confirm I am able to import the Metashape .nvm file into blender using your addon, which surprisingly imports the pointcloud (even though I just exported the cameras) but it doesn't appear to import the cameras

If you check the information in `Blender's info panel` you will find some messages like 
```
Corresponding image not found at: /home/sebastian/Desktop/100_7100.JPG
Invalid default values provided for width (-1) and height (-1)
Adjust the image path or the default width/height values to import the NVM / LOG file.
```

This is caused by the fact that the nvm file does not contain information about the image size. Either you can set them by hand (in the import options) or add the path to the images (in the import options). If you have installed pillow for blender (see [here](https://blender-addon-photogrammetry-importer.readthedocs.io/en/latest/installation.html#install-optional-dependencies)), the addon will automatically read the image sizes from disk.

**Comment by solosails** [comment]
Hmm, I do get the error you mentioned, but even by adding the path to the undistorted files, I still get no cameras - I do have all extensions (pillow etc) installed.

Metashape does rename the undistorted camera images though - could this be the issue?

Even without the camera background images, should I not be able to see the camera positions and animated track?

**Comment by solosails** [comment]
Ah, yes, if I manually re-name the undistort images to the original camera names - all as expected - phew - thanks!

**Comment by SBCV** [comment]
The names of the images are important, since the original image name is stored in the `nvm` file (and used to find the corresponding file on disk)

**Comment by solosails** [comment]
Understood, I also found a way to edit the naming of the Metashape undistort images to be the same as the original, so in the end all good - I can export model and animated cameras from Metashape using your amazing plugin - Thanks!

**Comment by solosails** [comment]
Hi there,

 

I just went to download and install your import agisoft photoscan plugin in Blender 2.93.4 , but it doesn’t seem to show up in the scene menu ? Am I doing something wrong? 

 

Best regards,

 

Andrew Wood.

 



 

Tel: 01736 366004

Mob: 07843 229941

www.solosails.com

**Comment by SBCV** [comment]
Just reinstalled the addon for 93.4 and it works without any issues.

Can you open a new issue and report more details there, such as:
- your operating system 
- is it a new system/pc where you tried to install the addon?
- If not, did you remove the old addon completely before installing it for 93.4?

Bests

**Comment by solosails** [comment]
Hi Sebastian,

 

Sorry for wasting your time, I just realised that I have mixed up two different plugins and authors! Yours works fine – sorry about that!!

 

Thanks!

 

Best regards,

 

Andrew Wood.

 



 

Tel: 01736 366004

Mob: 07843 229941

www.solosails.com

**Comment by SBCV** [comment]
Hi Andrew,
no problem.
Best regards,Sebastian

    Am Montag, 4. Oktober 2021, 10:30:05 MESZ hat Andrew Wood ***@***.***> Folgendes geschrieben:  
 
 

Hi Sebastian,

 

Sorry for wasting your time, I just realised that I have mixed up two different plugins and authors! Yours works fine – sorry about that!!

 

Thanks!

 

Best regards,

 

Andrew Wood.

 



 

Tel: 01736 366004

Mob: 07843 229941

www.solosails.com
