### ISSUE TITLE
Not loading mesh

### ISSUE THREAD

**Issue by claudito1991** [SBCV/Blender-Addon-Photogrammetry-Importer#31]
Hi there! i've just dowloaded the addon and followed the youtube tutorial and i'm having some troubles to load the mesh along with the point cloud ¿any toughts or work around this?

Blender 2.91
Windows 64 bit 20H2

**Comment by SBCV** [comment]
What are the exact problems you experience?
Did you execute the complete meshroom pipeline? If you want to import the mesh as well then you **must** execute (in Meshroom) also the _PrepareDense_, _DepthMap_, _DepthMapFilter_, _Meshing_, _MeshFiltering_ and _Texturing_ Node.
When importing the (the full) Meshroom reconstruction, navigate to the ***.mg** file and make sure that the import mesh option is selected.

**Comment by SBCV** [comment]
At the time I made that video, the addon did not support mesh imports

**Comment by claudito1991** [comment]
Hi there, thanks for the quick response. The problem was mine i was importing the .sfm not the .mg when i did what you told me the mesh got imported flawlessly. Now i have a doubt, i'm trying to clean my model in sculpt mode from the camera view by enabling and disabling the mesh visibility and i can't make the wireframes of the other cameras invisible without losing my background image reference. Is there any way to just see the camera and Bg image that i currently working on?

![image](https://user-images.githubusercontent.com/30451301/104389870-3107ba00-551b-11eb-9c26-ac9888e26d2e.png)

Visibility disabled but no background image

![image](https://user-images.githubusercontent.com/30451301/104389904-48df3e00-551b-11eb-97d4-8519cd7bfb73.png)

**Comment by claudito1991** [comment]
ok. I did a quick workaround by scaling my cameras to something like 0.001 so they don't bother my anymore. Thanks man, this is a great add on. YOU ROCK!

**Comment by SBCV** [comment]
I'm glad you solved your problem. I guess that "workaround" is probably the most reasonable approach to tackle this issue.
Thank you, it's always nice to get some feedback.
