### ISSUE TITLE
Importing as Point Cloud object or Mesh with Vertex Color

### ISSUE THREAD

**Issue by enzyme69** [SBCV/Blender-Addon-Photogrammetry-Importer#36]
Hi I tested the addon using Blender 2.92 so far so good. It also imports point data as Particle + instance + color. 

The mesh import currently only import points data, however like Blender import PLY, it does not seem to carry the point color data? I wish this addon can import it as Custom Attribute data? Which can be somewhat used by Geometry Nodes Modifier maybe in near future?

Ideally of course to be able to import point data as a real Point Cloud object in Blender?

What do you think about mesh data + vertex color + instance with those colors? Instead of Particles?

**Comment by SBCV** [comment]
This proposal sounds like a good idea! 
Find some comments and questions (inline) below.


> The mesh import currently only import points data, however like Blender import PLY, it does not seem to carry the point color data?

Do you mean with "mesh import" the import option highlighted with the red rectangle below?

![import_option](https://user-images.githubusercontent.com/19491335/110204167-03335780-7e72-11eb-8a7f-981b1bf2f32c.jpeg)

> I wish this addon can import it as Custom Attribute data?

Can you provide more details how to define the custom attribute data? Should the particle colors be represented by a list of colors? For example, something like 
```[(red_1, green_1, blue_1), (red_2, green_2, blue_2), ...]```

> Ideally of course to be able to import point data as a real Point Cloud object in Blender?

As far as I know, the new point cloud object (see https://developer.blender.org/T75717) has not been added yet. Or are you refering to something else?

> What do you think about mesh data + vertex color + instance with those colors? Instead of Particles?

Unfortunately, this `mesh data + vertex color + instance` is a bit unclear to me. Can you elaborate this a little bit?

**Comment by SBCV** [comment]
See 8cb5b4f

**Comment by SBCV** [comment]
Closed due to inactivity - feel free to re-open
