### ISSUE TITLE
Meshroom import

### ISSUE THREAD

**Issue by s-leger** [SBCV/Blender-Addon-Photogrammetry-Importer#4]
Hi, 
does this importer support both 2018 and 2019 meshroom files ? 
There are some differences in the json, and as 2019 still has some bugs i sometimes must rely on 2018 one.

**Comment by SBCV** [comment]
The repository contains an example JSON file (https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/master/examples/meshroom_example.json). I used this as reference to write the corresponding file handler. As you can see, the JSON file contains a version number. In this case it is ""version": ["1","0","0"]". 
Which version are you referring to?

**Comment by s-leger** [comment]
Can't confirm that .sfm file version number does change between Meshroom 2018 and Meshroom 2019, but there are differences in datastructure.
Eg: in 2018 .sfm file there is no view["metadata"]["Frame"], so you have to rely on file name (or another method).

**Comment by SBCV** [comment]
Oh, that's unfortunate ... Difficult to parse both versions without knowing the exact file format.
Side note: I do not use any of the metadata entries. So maybe it does work for both versions?
Do you know, if Meshroom 2018 and 2019 produce different *.BAF files as well?

**Comment by s-leger** [comment]
I only import .sfm as they are relevant for tracking import (as side note, .sfm is json formatted so no need to add a specific export node, unless there is another transformation than putting a .json extension)
In order to fix this issue, i end up to check the data structure for available field and rely on file names numbers as fallback when not found.

**Comment by SBCV** [comment]
I'm afraid I do not understand your exact problem / solution. 
Does the Addon import both file formats or not? If not, which .sfm/.json part causes the trouble?
Does it make sense to adjust the .sfm/.json file parser (https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/master/photogrammetry_importer/file_handler/meshroom_json_file_handler.py)?

**Comment by s-leger** [comment]
Are poseId enough to get ordered cameras to animate a camera along path ?
If so, frames and workaround are probably not required, and should work out of the box for both 2018 and 2019.

**Comment by SBCV** [comment]
Currently, the addon sorts the camera poses by the corresponding image names to define the motion path. Does this answer your question?

**Comment by s-leger** [comment]
Sometimes some images are "dropped" when there is not enough correspondences. Are the keyframes times using file number or simply stacking by order ?

**Comment by SBCV** [comment]
Currently, it uses only the actual reconstructed cameras. 
`    cameras_sorted = sorted(cameras, key=lambda x: x.file_name)

    for index, camera in enumerate(cameras_sorted):
        #op.report({'INFO'}, 'index: ' + str(index))

        current_keyframe_index = index * step_size

        cam_obj.matrix_world = compute_camera_matrix_world(camera)

        cam_obj.keyframe_insert(data_path="location", index=-1, frame=current_keyframe_index)

        # Don't use euler rotations, they show too many discontinuties
        #cam_obj.keyframe_insert(data_path="rotation_euler", index=-1, frame=current_keyframe_index)

        cam_obj.rotation_mode = 'QUATERNION'
        cam_obj.keyframe_insert(data_path="rotation_quaternion", index=-1, frame=current_keyframe_index)
        # q and -q represent the same rotation
        remove_quaternion_discontinuities(cam_obj)`

We could think of adding an option to consider non reconstructed cameras as well. Would this help?

**Comment by s-leger** [comment]
Probably might be usefull when some reconstructed are missing in the between, so the frames keep consistent with input footage.

**Comment by SBCV** [comment]
can you share an example file?

**Comment by s-leger** [comment]
Hi, will remove the folder tomorrow. Meshroom 2018 project, structure from motion and model, including blender 2.79 imported sfm with model.
https://www.dropbox.com/sh/mo43vi9rggzpx58/AABRpCtD15klgjwC25cRwpy5a?dl=1

**Comment by SBCV** [comment]
Thank for sharing the files. But I was actually looking for the JSON file with the SfM contents. Nevertheless, I've added some code that allows consider missing cameras during animation. Can you test the code, and report if it works for you as expected?

**Comment by s-leger** [comment]
you'll find sfm (json formatted) file in Meshroom/StructureFromMotion/cameras.sfm

**Comment by s-leger** [comment]
Ok, sucessfully imported .json ConvertSFMFormat exported one (84 Mo), as looks like .sfm (347k) file miss some informations.
But no luck, looks like it doesn't skip frames for non constructed data, even with images folder set.

As side note, you should use a 
subtype="DIR_PATH"
for image directory stringProperty in order to provide a "browse" button

**Comment by SBCV** [comment]
What do you mean with "But no luck, looks like it doesn't skip frames for non constructed data, even with images folder set. But no luck, looks like it doesn't skip frames for non constructed data, even with images folder set." Can you be more specific? 

Furthermore, adding subtype="DIR_PATH" to the string property is not possible, since this causes the following error: "Can not activate file selector, one already open"

**Comment by s-leger** [comment]
In motion tracking context, i expect missing reconstruction to skip a frame so camera motion timing match with footage.

**Comment by SBCV** [comment]
This is why I added a new option that allows to consider missing frames during camera animation. Can we close this issue?

**Comment by s-leger** [comment]
Frames are not properly skipped even with this option enabled (witch is default as far as i can tell)
I'll upload the motion .json on the dropbox folder so you may test.

**Comment by SBCV** [comment]
I just tested your file and the addon is doing what I expected it to do. 

Unfortunately, I do still not understand what are you struggling with. 
Can you clearly state your problem? 

Maybe the following points will help you to clarify the issue. 
1.) What is your goal? What do you want to achieve?
2.) What would you like the addon to do? (What is the meaning of "Frames are not properly skipped").  
3.) What happens instead?

**Comment by s-leger** [comment]
Hi,
I usually use Meshroom as motion tracker. Sadly sometimes some images can't be correctly tracked, and lead into missing reconstruction.

In order to better understand result i need, open the blender's file available on the github. 
Select the camera and take a look at keyframes, you'll see some frames without any key witch basically are frames missing reconstruction.

So when i do import such "motion" i expect no keyframe set for missing reconstruction, and instead skip that frame and add keys for next valid one in the exact same frame as original footage, after missing one so there is no time shift between movie images and camera motion every time the importer find a missing reconstruction.

**Comment by SBCV** [comment]
Are you talking about the `tracking.blend` file?

**Comment by s-leger** [comment]
yes

**Comment by SBCV** [comment]
But this has been not be computed with my addon?!?!

**Comment by s-leger** [comment]
Not this one, imported with another one, before you published yours.
Expected same result for moving camera with "Consider Missing .."

**Comment by SBCV** [comment]
Ok, I guess I understand your problem now. Can you share the images with me? Or at least the file names?

**Comment by s-leger** [comment]
Hi, unfortunately i can't share those files.
names are image0001.tif to image0242.tif

**Comment by SBCV** [comment]
Can you check out the latest version and check if it is working as expected?

**Comment by s-leger** [comment]
Hi, Yes checked and i can comfirm it does work as expected, properly skipping missing reconstruction frames, so camera animation now keep in synch with footage whatever the state of any particular frame.
Thank you !

**Comment by SBCV** [comment]
You're welcome
