### ISSUE TITLE
Exporting all locations of the animated camera

### ISSUE THREAD

**Issue by yyeboah** [SBCV/Blender-Addon-Photogrammetry-Importer#40]
Firstly, thanks for the wonderful plugin. I'm attempting to export all locations of the animated camera, including the interpolated locations and wondering if this is currently supported ?

I noticed that exporting the model outputs a single line for the current animated camera location. What I'd like to do is output multiple of such locations to file as said camera navigates the trajectory.

Thanks once again and looking forward to hearing from you.

**Comment by SBCV** [comment]
>I'm attempting to export all locations of the animated camera, including the interpolated locations and wondering if this is currently supported ?
The addon it self does provide such a functionality, but once you have imported your reconstruction, you can write a little python script to export the camera locations. All you (probably ) need to do is to something like this:

Get the animation indices from your scene
https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/f79c09ea9eda34574d20ed05ceda9226ce7f778c/photogrammetry_importer/blender_utility/retrieval_utility.py#L35
or your animated camera
https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/f79c09ea9eda34574d20ed05ceda9226ce7f778c/photogrammetry_importer/blender_utility/retrieval_utility.py#L41

and use these indices to iterate over your animation like here (i.e.  `bpy.context.scene.frame_set(idx)`).
https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/f79c09ea9eda34574d20ed05ceda9226ce7f778c/photogrammetry_importer/panels/render_operators.py#L136

Then you can write out the camera location with
`bpy.data.objects["name_of_camera"].location`

**Comment by yyeboah** [comment]
Thank you for the detailed explanation, I will be looking into it and see how it goes.
