### ISSUE TITLE
cant select in add-on

### ISSUE THREAD

**Issue by hdpklm** [SBCV/Blender-Addon-Photogrammetry-Importer#41]
![image](https://user-images.githubusercontent.com/35699848/133694977-a3852eee-62a5-4987-bd86-013e4f90eb37.png)

**Comment by SBCV** [comment]
That's strange, how did you install the addon / which version are you trying to install? Have you installed another (older) version previously?

**Comment by hdpklm** [comment]
i download the last version of photogrammetly from github and install in blender 2.8

**Comment by SBCV** [comment]
Oh, I've just noticed that your error message shows that you are using Blender 2.79 and not 2.8

**Comment by hdpklm** [comment]
yes, you are right is 2.79

**Comment by SBCV** [comment]
The current version of the addon does not work for Blender 2.79 - you need Blender 2.8 or higher
