### ISSUE TITLE
Importing files from WebODM failed

### ISSUE THREAD

**Issue by soeren68** [SBCV/Blender-Addon-Photogrammetry-Importer#42]
Hi,

I tried to import some files that were made in WebODM...
With the LAZ it worked, but it took very long time.
But I couldn't import any of the json-files, for example the "cameras.json"
I know that WebODM is based on OpenSFM, so I used that option.
Here is a link to a ZIP of all the files: https://testhub.dronedb.app/r/soeren68/42cjmkvjidqsbxaf
("all.zip" on top of the list)
Maybe you can analyze the files somehow and discover what's the problem with the WebODM output...

Greeting from Germany,
Sören

**Comment by SBCV** [comment]
Hi Sören, have you received some useful answer of the WebDOM developers?
