### ISSUE TITLE
Recursively starting Blender instances

### ISSUE THREAD

**Issue by toliman7** [SBCV/Blender-Addon-Photogrammetry-Importer#44]
Using blender 2.81a on MacOS.

Observed that the following code starts a new instance of Blender (preferences/dependency.py:Line:21):
```
    result = subprocess.run(
        [sys.executable, "-c", script_str],
        stdout=PIPE,
        stderr=PIPE,
    )
```
The intention seems to be to get the blender sys.path. Yet, instead of closing the instance it seems to call the same code again. This will recursively open new Blender instances.

For now I just changed Line:42:
`additional_system_paths = get_additional_command_line_sys_path()`
to
`additional_system_paths = []`

**Comment by SBCV** [comment]
Thank you for reporting this - that should really not happen. Unfortunately, I do not have MacOS, which makes debugging extremely difficult for me. Could you help me out here?

I  assume that executing

**Comment by toliman7** [comment]
The problem is the command line parameter "-c". Blender is not taking the second argument as script. I don't understand enough about the sys.path for Blender and what the difference to just calling "sys.path" is. Yet, I wonder if there is another way to retrieve Blender's sys.path "specialties".

See https://docs.blender.org/manual/en/latest/advanced/command_line/arguments.html

Let me know what I should debug.

**Comment by SBCV** [comment]
Ah, I guess I know what is happening here.

If i start Blender on Linux or Windows, go to Blender's python console and type:
```
import sys
print(sys.executable)
```
then I get the path to the **python** executable (of Blender)

Therefore, the code snippet 
```
subprocess.run(
        [sys.executable, "-c", script_str],
        stdout=PIPE,
        stderr=PIPE,
    )
```

is intended to call the **python** executable of Blender (and not Blender itself). 

I assume that under MacOS `sys.path` points to the location of the Blender executable. Is that correct?

**Comment by SBCV** [comment]
Therefore, we need on MacOS another way to determine the location of the Blender's python executable.

**Comment by SBCV** [comment]
You might wonder why I'm trying to run the content of the script in a subprocess. The reason for this is that (under windows and linux) Blender changes the values in `sys.path` (i.e. there is a difference when printing `sys.path` from the python console in Blender and the python console of the operating system)

Since the addon uses in this line
https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/d964ef04cefde73320749cc346113e16be5bd73b/photogrammetry_importer/preferences/dependency.py#L205

the following command to install the optional dependencies

```
        dependency_install_command = [
            self._get_python_exe_path(),
            "-m",
            "pip",
            "install",
            # https://pip.pypa.io/en/latest/cli/pip/?highlight=no-cache-dir#cmdoption-isolated
            # "--isolated",
            # https://pip.pypa.io/en/latest/cli/pip/?highlight=no-cache-dir#cmdoption-no-cache-dir
            "--no-cache-dir",
            self.package_name,
        ]
```

it is important to restore the missing paths of `sys.path` inside Blender. Otherwise the installed libraries might not work correctly.

**Comment by toliman7** [comment]
If I ran this within Python script:

```
import sys
print(sys.executable)
```
Output is the correct executable path:
`/Applications/Blender.app/Contents/MacOS/Blender`

`print(sys.path)`
brings:

```
['/Applications/Blender.app/Contents/Resources/2.81/scripts/startup', '/Applications/Blender.app/Contents/Resources/2.81/scripts/modules', '/Applications/Blender.app/Contents/Resources/2.81/python/lib/python37.zip', '/Applications/Blender.app/Contents/Resources/2.81/python/lib/python3.7', '/Applications/Blender.app/Contents/Resources/2.81/python/lib/python3.7/lib-dynload', '/Applications/Blender.app/Contents/Resources/2.81/python/lib/python3.7/site-packages', '/Applications/Blender.app/Contents/Resources/2.81/scripts/freestyle/modules', '/Applications/Blender.app/Contents/Resources/2.81/scripts/addons/modules', '/Users/daniel/Library/Application Support/Blender/2.81/scripts/addons/modules', '/Applications/Blender.app/Contents/Resources/2.81/scripts/addons', '/Users/daniel/Library/Application Support/Blender/2.81/scripts/addons', '/Applications/Blender.app/Contents/Resources/2.81/scripts/addons_contrib']
```

Now doing the same at dependency.py by printing out `blender_sys_paths = copy.deepcopy(sys.path)` at line 27:

```
['Blender.app/Contents/Resources/2.81/scripts/startup',
'Blender.app/Contents/Resources/2.81/scripts/modules', '/Applications/Blender.app/Contents/Resources/2.81/python/lib/python37.zip', '/Applications/Blender.app/Contents/Resources/2.81/python/lib/python3.7', '/Applications/Blender.app/Contents/Resources/2.81/python/lib/python3.7/lib-dynload', '/Applications/Blender.app/Contents/Resources/2.81/python/lib/python3.7/site-packages', 'Blender.app/Contents/Resources/2.81/scripts/freestyle/modules', 'Blender.app/Contents/Resources/2.81/scripts/addons/modules', '/Users/daniel/Library/Application Support/Blender/2.81/scripts/addons/modules', 'Blender.app/Contents/Resources/2.81/scripts/addons', '/Users/daniel/Library/Application Support/Blender/2.81/scripts/addons', 'Blender.app/Contents/Resources/2.81/scripts/addons_contrib']
```

Yes, there are differences between `sys.path` inside blender and calling the blender python externally. But it probably won't need the extra subprocess to determine that. Just replace use the content of `blender_sys_paths` in the  install command. It uses the python inside the blender installation. No need to add any additional paths for MacOS.

**Comment by SBCV** [comment]
I've just realized that the error you observe is probably unrelated to MacOS.
As you can see in the following code snipped
```
def _get_python_exe_path():
    # https://developer.blender.org/rB6527a14cd2ceaaf529beae522ca594bb250b56c9
    try:
        # For Blender 2.80, ..., etc
        python_exe_fp = bpy.app.binary_path_python
    except AttributeError:
        # For Blender 2.92, ..., etc
        python_exe_fp = sys.executable
    return python_exe_fp
```
of this line
https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/39d0ae216c2d6fb5a646e3394bbb6c7506a74c9b/photogrammetry_importer/preferences/dependency.py#L18
there is a difference how Blender 2.8 and 2.9 / 3.0 are accessing the python executable path.

Because of that the code snipped
```
subprocess.run(
        [sys.executable, "-c", script_str],
        stdout=PIPE,
        stderr=PIPE,
    )
```
should actually be

```
subprocess.run(
        [_get_python_exe_path(), "-c", script_str],
        stdout=PIPE,
        stderr=PIPE,
    )

```
I've added a patch for this in the latest commit (39d0ae216c2d6fb5a646e3394bbb6c7506a74c9b). Can you test this version and check if everything works for you?

**Comment by SBCV** [comment]
Added also a new release [here](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/releases/tag/v2022.01.17)

**Comment by toliman7** [comment]
Tested successfully on Blender 2.81a on MacOS Monteray:

```
Read prefs: /Users/daniel/Library/Application Support/Blender/2.81/config/userpref.blend
found bundled python: /Applications/Blender.app/Contents/Resources/2.81/python
INFO:root:INFO: Registered Photogrammetry Import Export Addon with 53 modules
INFO:root:INFO: Found installed dependencies. Going to adjust sys.path.
```

**Comment by toliman7** [comment]
Tested successfull yon Blender 3.0 on MacOS Monteray!

Thanks for the fix.

**Comment by SBCV** [comment]
Perfect, thank you for reporting and testing. This helps so much to maintain the software.
