### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by luminati** [SBCV/Blender-Addon-Photogrammetry-Importer#5]
I can't get it to work. Tried all the variations for the path as well as leaving string empty and coping images to json folder and always get this error:
Traceback (most recent call last):
  File "C:\Users\Adm\Desktop\blender-2.80-windows64\2.80\scripts\addons\photogrammetry_importer\photogrammetry_import_op.py", line 200, in execute
    path, self.path_to_images, self)
  File "C:\Users\Adm\Desktop\blender-2.80-windows64\2.80\scripts\addons\photogrammetry_importer\file_handler\meshroom_json_file_handler.py", line 146, in parse_meshroom_file
    cams, image_index_to_camera_index = MeshroomJSONFileHandler.parse_cameras(json_data, op)
  File "C:\Users\Adm\Desktop\blender-2.80-windows64\2.80\scripts\addons\photogrammetry_importer\file_handler\meshroom_json_file_handler.py", line 23, in parse_cameras
    views = json_data['views']              # is a list of dicts (view)  
KeyError: 'views'

location: <unknown location>:-1

**Comment by SBCV** [comment]
This error is not related to the image folder location, but to the structure of the JSON file. As s-leger pointed out in #4, Meshroom changed its JSON format. Can you share your JSON file? What is the version number of your JSON file?

**Comment by SBCV** [comment]
Can you share your JSON file?

**Comment by luminati** [comment]
[stats.zip](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/files/3492122/stats.zip)

**Comment by SBCV** [comment]
This is not the "correct" JSON file. It does neither contain reconstructed camera poses nor 3D points. Please take a look at the example provided here (https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/tree/master/examples). Your JSON file must have a similar structure. 

In Meshroom add a "ConvertSfMFormat" node and connect it with the StructureFromMotion node (see image below)
![meshroom_export_json](https://user-images.githubusercontent.com/19491335/62863311-b5dc1c00-bd08-11e9-9798-e7d5666c3f8c.jpg)

Then use the JSON file, which is created by the "ConvertSfMFormat" node.

**Comment by luminati** [comment]
Ok it works now. :) Can I ask why addon changes rendering engine to Cycles?

**Comment by SBCV** [comment]
Earlier versions of the addon, were desigend for Blender 2.79. There, only Cycles supported the node system used to visualize the images. I guess, I should update the corresponding part. Thank you for the advice.

**Comment by luminati** [comment]
Another change in 2.8 in comparison to 2.79 is that background images are now assigned to a specific camera, not globally. So it is possible to make each image visible only in the correct camera. It helps when there are many cameras that obstruct the view of the other cameras as well as makes manipulations of the images and geometry behind it a lot easier. Maybe you could consider adding an option to import images into background images instead of image planes as well?

**Comment by SBCV** [comment]
In the latest version is now an option available to add background images. Thank you for the suggestion.

**Comment by luminati** [comment]
Awesome! Wow, that was quick. Thank you :)

**Comment by luminati** [comment]
Just heads up. There's a bug in the current stable version of blender and background images import with a weird offset in relation to the camera. In nightly build, it works ok.

**Comment by SBCV** [comment]
Thank you for point this out!
