### ISSUE TITLE
How is managed lens distorsion by this addon?

### ISSUE THREAD

**Issue by trenoduro** [SBCV/Blender-Addon-Photogrammetry-Importer#53]
I exported from Agisoft Metashape both camera poses (using .nvm format), **undistorted pictures** as jpegs and markers as dxf.

I later imported the .nvm in blender using this extension alongside the .dxf with the marker location.

Sadly markers are misplaced in respect to their feature points as you can see from the attached picture

![Snipaste_2022-11-22_15-54-20](https://user-images.githubusercontent.com/22579965/203346047-c8f47a4f-023f-4909-9368-ee7565f5e52d.jpg)

As you can see in Metashape this markers are perfectly placed (screenshot taken from 3d view looking through the camera) 
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/22579965/203346421-312ee6ee-1fdc-4ebe-b9ba-a8ad1d6a457b.png">

**Comment by SBCV** [comment]
Regarding to your question "How is managed lens distortion by this addon?".

Just to avoid any confusion: Blender does not support distorted camera models (in the 3D view).
Thus, the addon requires camera models with intrinsic parameters relative to undistorted images.
You can find some more information [on this page in the documentation](https://blender-photogrammetry-importer.readthedocs.io/en/latest/alignment.html).

> I exported from Agisoft Metashape both camera poses (using .nvm format), undistorted pictures as jpegs and markers as dxf.
> I later imported the .nvm in blender using this extension alongside the .dxf with the marker location.
> Sadly markers are misplaced in respect to their feature points as you can see from the attached picture

Reading your description, I guess you are loading some inconsistent data (i.e. some data that is defined relative to the reconstructed (distorted) cameras, and some other data that is defined relative to the UNdistorted cameras).

What you need to find out: 
- Are the intrinsic camera parameters in the .nvm file defined relative to the original images / or the undistorted images 
- Are the markers in the dfx file defined relative to the original images / or the undistorted images 

Question: Do you really need a camera model with distortion parameters? If the distortion is small you can usually use camera model without distortion parameters (and the result will be sufficiently accurate).

Btw: I do no know the dxf file format. So I have no idea what is happening when you are importing this file. Can you share a link?

**Comment by trenoduro** [comment]
Hi, i managed to solve the problem. In short it was Metashape that was exporting bad UNdistorted images based on the uncalibrated focal length, when setting the correct focal length in metashape everything aligned properly in Blender.

For anyone facing same problem just put the adjusted focal in the precalibrated field like this before exporting undistorted images:
![image](https://user-images.githubusercontent.com/22579965/204091674-392aa80f-7d6c-407d-a96e-58fe7c3c0a36.png)

**Comment by SBCV** [comment]
Hey, thank you for reporting a solution to this pitfall - I'm sure it will be useful for others :)
