### ISSUE TITLE
Importing a .nvm from metashape radial distortion warning

### ISSUE THREAD

**Issue by henrypearce4D** [SBCV/Blender-Addon-Photogrammetry-Importer#59]
First I have to say wow this project is great! I'm so happy I found it!

I'm getting a warning after importing a .nvm from metashape;
`INFO:root:WARNING: Blender does not support radial distortion of cameras in the 3D View. Distortion of camera Cam001.jpg: {radial_distortion}. If possible, re-compute the reconstruction using a camera model without radial distortion parameters.  Use "Suppress Distortion Warnings" in the import settings to suppress this message.`

The set does import but looking through the cameras the background image doesn't line up, I presume because of this warning, any advice?

**Comment by SBCV** [comment]
Sorry for the late reply - I'm traveling at the moment. If your camera has no radial distortion you can usally set this parameter to 0 during the reconstruction process. If you import the distortion free results, they should properly align in Blender.

**Comment by SBCV** [comment]
See also: https://blender-photogrammetry-importer.readthedocs.io/en/latest/alignment.html

**Comment by henrypearce4D** [comment]
Thankyou for the info, so the popup is an error and a warning, but blender ignores this?
If I export the scene from blender as a colmap model the cameras should align with the undistorted from metashape?

**Comment by SBCV** [comment]
The export function extracts only the 3D structure (scene points, cameras) of the reconstruction - not the corresponding feauture points. If you want convert your reconstruction results, you might be interested in: https://github.com/naver/kapture

**Comment by SBCV** [comment]
If you want consistent results in Blender, use for example Colmap and perform not only SfM but also Multi-View Stereo. If you import the undistorted images (and the corresponding cameras), the imported results should be consistent.

**Comment by henrypearce4D** [comment]
Thankyou! I really appreciate you taking the time to link this!
