### ISSUE TITLE
Meshroom Sfm data version 1.2.4

### ISSUE THREAD

**Issue by bhack** [SBCV/Blender-Addon-Photogrammetry-Importer#60]
Do you plan to support 1.2.4 version? 
In the meantime Is there any other workaround to work with new Meshroom versions?

https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/f03cd181c25123fa53dd15086f3115678560a80e/photogrammetry_importer/file_handlers/meshroom_file_handler.py#L135-L136

**Comment by SBCV** [comment]
Hey, I'm traveling right now. I'll fix this once I'm back. Feel free to submit a pull request

**Comment by SBCV** [comment]
The latest meshroom version raised the sfm data version without introducing new semantic changes. Fixed in [this commit](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/commit/7dc5d44423a01a8a56a0e141be3c102672c50d14)
