### ISSUE TITLE
Can't see image plane from colmap

### ISSUE THREAD

**Issue by Khoa-NT** [SBCV/Blender-Addon-Photogrammetry-Importer#64]
Hi, thank you for the great plugin

I tried to import colmap following this [video](https://www.youtube.com/watch?v=NDT5zhhfQvo)
Colmap: `Blender-Addon-Photogrammetry-Importer/examples/colmap_example_model_bin/`
Image: `ImageDataset_SceauxCastle/images/`
![image](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/assets/12138158/79cad6ed-4940-45fd-a1ca-ccf886826099)

However, I can't see the image planes
![image](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/assets/12138158/9ec675a9-e28f-4742-8fe1-febfb2a2ed90)

Is it because I'm using Blender Version 3.6.0 (3.6.0 2023-06-27)?
Can someone support me?

**Comment by SBCV** [comment]
I think you set the `shading`  in the viewport to `Material Preview` or `Rendered`. In your example image it is set to `solid`.

See the red rectangle in the following image: 
![image](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/assets/19491335/bdeca3e1-3318-4707-ae1d-804f7a6423ab)

**Comment by Khoa-NT** [comment]
Thank you. It works.
Can I ask how I can align the whole thing (camera poses, image planes, etc.) to the Z+ axis instead of the Y axis like in the example? 
Because It's hard for me to rotate with the mouse.

**Comment by SBCV** [comment]
In the past I solved this by selecting all objects (for example by pressing `a` in the viewport) and then rotating the selected objects by pressing `r` and moving the mouse. But that is probably not the only way.
