### ISSUE TITLE
Blender 2.81 ?

### ISSUE THREAD

**Issue by 6eye** [SBCV/Blender-Addon-Photogrammetry-Importer#9]
Might be Installation problem in 2.81. Though installed it is not showing .SFM format type in Import menu

**Comment by SBCV** [comment]
I tried to recreate this issue without success (i.e. the addon is working as expected using Blender 2.81a).

Have you activated the addon after installation? (I have added some more installation instructions [here](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/blob/master/doc/markdown/installation.md)).
Can you see the other import options? 
Has the addon worked for you with an older version of Blender?

**Comment by 6eye** [comment]
Yes it's working now after installation of 2.81a.

**Comment by SBCV** [comment]
Thank you for the feedback
